import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
// import Header from "@/components/layout/Header";
import { AuthProvider } from "@/components/providers/auth-providers";
import { NotificationPermission } from "@/components/notificationPermission";
import { DialogProvider } from "@/components/providers/DialogProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider
            protectedRoutes={[
              "/coordinates-generator",
              "/excel",
              "/json",
              "/odp-tools",
              "/scrape",
              "/whatsapp",
              "/wa",
              "/dashboard",
            ]}
          >
            <DialogProvider>
              {/* <Header /> */}
              <main className="container max-w-screen sm:px4">
                {children}
                <NotificationPermission />
              </main>
              <Toaster expand={true} closeButton theme="dark" richColors />
            </DialogProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
